language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade pip
  - git clone https://github.com/google/jax-md
  - pip install -e jax-md
script:
  - for f in jax-md/tests/*.py; do python $f; done
